### ISSUE TITLE
Disable seeds

### ISSUE THREAD

**Issue by romaust** [CodersDownUnder/FlowerSeeds#8]
Disable seeds for mods, that is not installed. Because sometimes in the dungeons from mods, wich contain some of ther plants can have this kind of plant
![2022-11-20_12 57 12](https://user-images.githubusercontent.com/86145355/202898481-029b5f17-9f8c-4276-9bfa-30b06f75c7aa.png)

**Comment by Trhod17** [comment]
Which mod is this dungeon from?

**Comment by romaust** [comment]
[Dungeon Crawl](https://www.curseforge.com/minecraft/mc-mods/dungeon-crawl)

**Comment by xenornithos** [comment]
Still an issue, that I'm also encountering -- I notice these are for **BYG** and **Cyclic**, both of which I don't have installed, so this odd texture appears instead. There's no notable option to disable these, which would be highly favoured (or some way for them to not generate if the mods _aren't_ included).

Is this something that can be fixed in this mod, or an issue with **Dungeon Crawl**? Is it possible to disable their generation regardless, if BYG/Cyclic aren't installed alongside Flower Seeds?

**Comment by Trhod17** [comment]
Should be fixed in flowerseeds2 https://www.curseforge.com/minecraft/mc-mods/flower-seeds
